class AppConstants:
    CODE_INVALID_REQUEST = 400
    DATA_NOT_FOUND = 404
    CODE_INTERNAL_SERVER_ERROR = 500
    SUCCESSFULL_STATUS_CODE = 200
    UNSUCCESSFULL_STATUS_CODE = 500
    CREATE_SUCCESSFUL = 201
    USER_ALREADY_EXISTS = 409
    UNAUTHORIZED_ACCESS = 401 
    CODE_INSUFFICIENT_TOKENS = 402
    PASSWORD_CHANGE_SUCCESS = 202
    CODE_SUCCESS = 200
    CODE_UPGRADE_PROMPT = 402 
    



